version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl

            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - '*'
      - run:
          name: config
          command:
            mv ecssweb/settings.example.py ecssweb/settings.py

  unit_test:
    docker:
        - image: circleci/python:3.6.1-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            python manage.py test
  coverage:
    docker:
        - image: circleci/python:3.6.1-browsers
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: coverage
          command: |
            . venv/bin/activate
            pip install --upgrade pip
            pip install coverage
            pip install codacy-coverage
            coverage run --source='.' manage.py test
            coverage report
            coverage xml
            export CODACY_PROJECT_TOKEN=$COVERAGE_TOKEN
            python-codacy-coverage -r coverage.xml

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
                - seleniumSetup
      - unit_test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - seleniumSetup
      - coverage:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
                - seleniumSetup
